### ISSUE TITLE
Crash: Unfortunately, project magente has stopped

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#156]
This has happened with today nightly build  eec3399:
1. Tapping on an event in a sched tile in the expanded view: https://mzl.la/schgw2 (Ideation Skill Build Intro)
2. Trying to do something like retweet from the twitter tile in the expanded view: https://mzl.la/twtldn

Only android build is affected.

**Comment by wilsonpage** [comment]
This is the Java exception:

```
06-11 09:37:53.280 32386-32386/? W/System.err: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
06-11 09:37:53.281 32386-32386/? W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:1269)
06-11 09:37:53.281 32386-32386/? W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:1256)
06-11 09:37:53.281 32386-32386/? W/System.err:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:329)
06-11 09:37:53.281 32386-32386/? W/System.err:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:329)
06-11 09:37:53.281 32386-32386/? W/System.err:     at org.mozilla.magnet.webview.MagnetWebViewClient.shouldOverrideUrlLoading(MagnetWebViewClient.java:61)
06-11 09:37:53.281 32386-32386/? W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:336)
06-11 09:37:53.281 32386-32386/? W/System.err:     at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:168)
06-11 09:37:53.281 32386-32386/? W/System.err:     at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:256)
06-11 09:37:53.281 32386-32386/? W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
06-11 09:37:53.281 32386-32386/? W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
06-11 09:37:53.281 32386-32386/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-11 09:37:53.281 32386-32386/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
06-11 09:37:53.282 32386-32386/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5294)
06-11 09:37:53.282 32386-32386/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-11 09:37:53.282 32386-32386/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-11 09:37:53.282 32386-32386/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
06-11 09:37:53.282 32386-32386/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by isabelrios** [comment]
Verified on 4f627c8.
