### ISSUE TITLE
Crash opening notification

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#283]
```
java.lang.IllegalStateException: GoogleApiClient is not connected yet.
    at com.google.android.gms.internal.zzrb.zzb(Unknown Source)
    at com.google.android.gms.internal.zzrf.zzb(Unknown Source)
    at com.google.android.gms.internal.zzrd.zzb(Unknown Source)
    at com.google.android.gms.location.internal.zzd.removeLocationUpdates(Unknown Source)
    at org.mozilla.magnet.scanner.geolocation.ScannerGeolocation.stop(ScannerGeolocation.java:83)
    at org.mozilla.magnet.scanner.MagnetScanner.stop(MagnetScanner.java:112)
    at org.mozilla.magnet.MagnetScannerReact.stop(MagnetScannerReact.java:52)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
    at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:148)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by wilsonpage** [comment]
Moved to https://github.com/mozilla-magnet/magnet-scanner-android/issues/16
